// Copyright 2026, Daniel Scholl
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

import type { RibDocsSource } from "@keelson/shared";

export const DOCS: readonly RibDocsSource[] = [
  {
    title: "ADME",
    summary:
      "The ADME rib for Keelson: an admin surface for one Azure Data Manager for Energy instance, worked from the operator's Azure CLI sign-in.",
    content: [
      "# ADME rib",
      "",
      "Administers one Azure Data Manager for Energy (ADME) instance from one",
      "ADME tab with three sections, picked in its header: Access (people and",
      "applications), Data (services, legal tags, record counts and record",
      "search; read-only) and Seismic (subprojects and who can reach them). The",
      "header also carries the connection: the instance, who is signed in, and",
      "Connection details, which opens the profile and capabilities in a drawer.",
      "",
      "## Connecting",
      "",
      "The rib holds no secret. The operator runs `az login --tenant <tenant id>`",
      "in a terminal. The ADME header then lists the ADME instances that",
      "sign-in can see in Azure, across every subscription, and Connect on one",
      "saves its host, partition, tenant id and ADME app id as the profile. An",
      "operator with no Azure role on the instance enters those four by hand.",
      "Test connection makes about eight read-only calls, reads the entitlements",
      "domain from the instance, and records what the sign-in can do; a missing",
      "capability disables the feature that needs it, with a reason. The roster",
      "group id is optional: the rib offers an Entra group named after the",
      "instance, and the operator confirms it.",
      "",
      "Before each batch of calls the rib asks `az account get-access-token` for",
      "tokens for the ADME app id and for Microsoft Graph. When the sign-in",
      'lapses every section reads "sign-in needed", shows the last sweep marked',
      '"cached from HH:MMZ", and pauses changes until `az login` and Re-test.',
      "",
      "## Reads",
      "",
      "A sweep runs on Refresh now, after Re-test, and on a timer only within 15",
      "minutes of the last operator action. The last sweep is cached in the rib's",
      "data directory. Record totals are summed from search's aggregate by kind,",
      "because search caps its own total at 10,000.",
      "",
      "## People and applications",
      "",
      "Access reads the members of users@ and the four role groups",
      "(viewers, editors, admins, ops) and resolves each id through Microsoft",
      "Graph. A person is healthy, pending (invited, not accepted) or broken:",
      "holding a role without users@, or listed twice in one group by object id",
      "and by email. The Access count counts pending plus broken. Entitlements",
      "lists applications by app id; an id Entra does not know is shown as an",
      "unknown principal.",
      "",
      "## Seismic",
      "",
      "The seismic store is not read by the sweep. The Seismic section reads it",
      "on first use (Read subprojects, or any action in the section), on Refresh",
      "now while the section shows, and after Re-test once it has been used.",
      "The subproject list carries each subproject's admin and viewer groups;",
      "the rib reads those groups' members and names them through the people",
      "read. Groups under data.default are not read: those subprojects are",
      "reached by everyone with a data role. The instance's own app and",
      "users.data.root sit in every group and are not counted as grants. When",
      "the list or a member list is refused, the rib falls back to the",
      "operator's own data.sdms groups and marks the result partial.",
      "",
      "## Cohorts",
      "",
      "The instance cannot say which cohort a person belongs to or when a pass",
      "ends, so the rib keeps a tracker per instance in its data directory.",
      "Everyone starts untracked. Import cohorts in the Access section takes",
      "one person per line as `email, cohort, pass end` (the date is optional,",
      "YYYY-MM-DD); one bad line refuses the whole import. Importing changes",
      "only the tracker, never the instance. Export roster writes a cohort's",
      "people as CSV under `exports/` in the data directory.",
      "",
      "## Changes",
      "",
      "Every change is a previewed plan: a form submits Preview plan and never",
      "writes. Apply re-runs the dry run first. The Data section never writes.",
      "",
      "## Data handling",
      "",
      "Names, email addresses and object ids are plain text in board frames and",
      "in the data directory, which suits one operator on a local workbench.",
      "Selection, including the section, is held by the rib, so two browser",
      "windows share one view.",
    ].join("\n"),
  },
];
